const PRIVATE_KEY = "coder39760";

const ROLES = {
    USER: "USER",
    PREMIUM: "PREMIUM",
    ADMIN: "ADMIN",
    PUBLIC: "PUBLIC",
};

const PUBLIC_ACCESS = [ROLES.PUBLIC];
const PRIVATE_ACCESS = [ROLES.USER, ROLES.PREMIUM, ROLES.ADMIN];
const PREMIUM_ACCESS = [ROLES.PREMIUM, ROLES.ADMIN];
const ADMIN_ACCESS = [ROLES.ADMIN];
const CARTS_ACCESS = [ROLES.USER, ROLES.PREMIUM];
export {
    PRIVATE_KEY,
    ROLES,
    PUBLIC_ACCESS,
    PRIVATE_ACCESS,
    PREMIUM_ACCESS,
    ADMIN_ACCESS,
    CARTS_ACCESS,
};
